version: '3.4'

networks:
    barracuda-service:
        driver: bridge
        
services:
    barracuda-socket-server:
        image: barracuda-socket-server:latest
        depends_on:
            - "postgres_image"
            - "barracuda-api"
        ports:
            - "5206:80"
        build:
            context: .
            dockerfile: src/Barracuda.SocketServer/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        networks:
            - barracuda-service

    barracuda-api:
        image: barracuda-api:latest
        depends_on:
            - "postgres_image"
        ports:
            - "5106:80"
        build:
            context: .
            dockerfile: src/Barracuda.WebApi/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        networks:
            - barracuda-service
        
    postgres_image:
        image: postgres:latest
        ports:
            - 5432:5432
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "abdurrahman"
            POSTGRES_PASSWORD: "ibanez21"
            POSTGRES_DB: "barracuda-prod"
        networks:
            - barracuda-service
            
volumes:
    db_volume: